# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='attachment',
            field=models.FileField(blank=True, default=None, upload_to='reviews'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 30, 11, 15, 20, 864472, tzinfo=utc)),
        ),
    ]
