# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20170730_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mail',
            field=models.EmailField(default='a@a.com', max_length=254, verbose_name='Ваш e-mail'),
        ),
        migrations.AddField(
            model_name='review',
            name='theme',
            field=models.CharField(default='Без темы', max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='review',
            name='attachment',
            field=models.FileField(blank=True, default=None, upload_to='reviews', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=75, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
