# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170521_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_avatar',
            field=models.ForeignKey(default='ch3rny', on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
            preserve_default=False,
        ),
    ]
