# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 10:13
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Оставьте ваш комментарий:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=sorl.thumbnail.fields.ImageField(default='avatar.png', upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
