# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 20:29
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170705_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='blog.UserProfile', verbose_name='Лукасы'),
        ),
        migrations.AddField(
            model_name='post',
            name='watched',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=sorl.thumbnail.fields.ImageField(default='avatar.png', upload_to='avatars', verbose_name='Аватар'),
        ),
    ]
